# The base URL of the site.
base_url = "https://luna.inakaz.fr/"

# To avoid problems with some variables due to multilingual support,
# you will find repeated variables in the language section,
# it is recommended that you keep those of your language and the general
# ones with the same data.
default_language = "fr"
#theme = "ataraxia"

# To find a detailed description of the following configuration variables
# you can go to https://www.getzola.org/documentation/getting-started/configuration/

output_dir = "public"

build_search_index = true
generate_feed = true
feed_filename = "atom.xml"
# feed_limit = 20

compile_sass = false

minify_html = false
hard_link_static = false

# ignored_content = []


[extra]
    author = "Luna"

    # Use a square image (same height as width)
    avatar = "assets/images/avatar.png"

    # To use a favicon convert your image to https://realfavicongenerator.net/,
    # then download and copy the package to static/images/favicon
    favicon = true
    locale = "fr_FR"

    # Ataraxia uses Bootstrap icons,
    # you can go to https://icons.getbootstrap.com/ to find the full list
    [extra.menus]
        nav = [
            { name = "Accueil", url = "@/_index.md", icon = "bi-house" },
            { name = "Contact", url = "@/_index.md#contact", icon = "bi-envelope" },
            { name = "Projets", url = "#", icon = "bi-box" },
            { name = "Blog", url = "@/blog/_index.md", icon = "bi-file-earmark-text" },
            { name = "Faire un don", url = "@/blog/_index.md", icon = "bi-currency-euro" },
            { name = "A propos", url = "https://github.com/gersonbdev/ataraxia-zola", icon = "bi-question-octagon" }
        ]
    
    [extra.social]
        author_link = "/"
        links = [
            { name = "Email", url = "mailto:your-user@email.com", icon = "bi-envelope-fill" },
            { name = "GitHub", url = "https://github.com/", icon = "bi-github" },
            { name = "Mastodon", url = "https://twitter.com/", icon = "bi-mastodon" },
            { name = "Instagram", url = "https://www.linkedin.com/", icon = "bi-instagram" },
            { name = "Spotify", url = "https://www.facebook.com/", icon = "bi-spotify" },
            { name = "Autres", url = "/#contact", icon = "bi-three-dots" }
        ]

    [extra.comments]
        disqus = "user"

    [extra.copyright]
        name = "CC BY 4.0"
        url = "https://creativecommons.org/licenses/by/4.0/"


[languages]
    [languages.fr]
        title = "Luna"
        description = "Moi, c'est Luna (elle). Je vis en Bretagne et j'étudie de Saint-Nazaire."
        generate_feed = true
        feed_filename = "atom.xml"
        taxonomies = [
            { name = "tags", feed = true, paginate_by = 5  },
            { name = "categories", feed = true, paginate_by = 5 },
            { name = "projets", feed = true, paginate_by = 5 }
        ]

    [languages.en]
        title = "Nombre del sitio web"
        description = "Descripción del sitio web"
        generate_feed = true
        feed_filename = "atom.xml"
        taxonomies = [
            { name = "tags", feed = true, paginate_by = 5  },
            { name = "categories", feed = true, paginate_by = 5 }
        ]


    [languages.fr.translations]
        post = "Posté"
        category = "Categorie"
        tag = "Tag"
        search = "Rechercher"

        404_message = "Cette page n'existe pas ou plus !"

        by = "Par"
        posted = "Posté"
        updated = "Mis à jour"
        categories = "Catégories"
        tags = "Tags"
        share = "Partager"
        
        next = "Suivant"
        previous = "Précédent"

        short_copyright = "Some rights reserved."
        full_copyright = """\
            Except where otherwise noted, the blog posts on this site are \
            licensed under the Creative Commons Attribution 4.0 International \
            (CC BY 4.0) License by the author.\
            """

    [languages.en.translations]
        post = "Entrada"
        category = "Categoría"
        tag = "Etiqueta"
        search = "Buscar"

        404_message = "Página no encontrada"

        by = "Por"
        posted = "Publicado"
        updated = "Actualizado"
        categories = "Categorías"
        tags = "Etiquetas"
        share = "Compartir"
        
        next = "Siguiente"
        previous = "Anterior"
        
        short_copyright = "Algunos derechos reservados."
        full_copyright = """\
            Salvo que se indique explícitamente, las entradas de este blog \
            están licenciadas bajo la Creative Commons Attribution 4.0 \
            International (CC BY 4.0) License por el autor.\
            """


[markdown]
    highlight_code = true
    # extra_syntaxes_and_themes = []
    highlight_theme = "gruvbox-dark"

    render_emoji = true


    external_links_target_blank = true
    external_links_no_follow = true
    external_links_no_referrer = true

    smart_punctuation = false


[search]
    include_title = true
    include_description = false
    include_path = false
    include_content = true
    # truncate_content_length = 100


[link_checker]
    # skip_prefixes = []
    # skip_anchor_prefixes = []

    internal_level = "error"
    external_level = "error"


[slugify]
    paths = "on"
    taxonomies = "on"
    anchors = "on"