# The base URL of the site.
base_url = "https://luna.inakaz.fr/"

# To avoid problems with some variables due to multilingual support,
# you will find repeated variables in the language section,
# it is recommended that you keep those of your language and the general
# ones with the same data.
default_language = "fr"
#theme = "ataraxia"

# To find a detailed description of the following configuration variables
# you can go to https://www.getzola.org/documentation/getting-started/configuration/

output_dir = "public"

build_search_index = true
generate_feed = true
feed_filename = "atom.xml"
# feed_limit = 20

compile_sass = false

minify_html = false
hard_link_static = false

# ignored_content = []


[extra]
    author = "Luna"

    # Use a square image (same height as width)
    avatar = "images/avatar.png"

    # To use a favicon convert your image to https://realfavicongenerator.net/,
    # then download and copy the package to static/images/favicon
    favicon = true
    locale = "fr_FR"

    # Ataraxia uses Bootstrap icons,
    # you can go to https://icons.getbootstrap.com/ to find the full list
    [extra.menus]
        nav = [
            { name = "Accueil", url = "@/_index.md", icon = "bi-house" },
            { name = "Contact", url = "@/_index.md#contact", icon = "bi-envelope" },
            { name = "Projets", url = "#", icon = "bi-box" },
            { name = "Blog", url = "@/blog/_index.md", icon = "bi-file-earmark-text" },
            { name = "Faire un don", url = "@/blog/_index.md", icon = "bi-currency-euro" },
            { name = "A propos", url = "https://github.com/gersonbdev/ataraxia-zola", icon = "bi-question-octagon" }
        ]
    
    [extra.social]
        author_link = "/"
        links = [
            { name = "Email", url = "mailto:luna@kaz.fr", icon = "bi-envelope-fill" },
            { name = "GitHub", url = "https://github.com/lunanarch", icon = "bi-github" },
            { name = "Mastodon", url = "https://todon.eu/@chasociale", icon = "bi-mastodon" },
            { name = "Instagram", url = "https://instagram.com/lunanarch", icon = "bi-instagram" },
            { name = "Soundcloud", url = "https://soundcloud.com/lchl", icon = "bi-music-note-beamed" },
            { name = "Autres", url = "/#contact", icon = "bi-three-dots" }
        ]

    [extra.comments]
        disqus = "user"

    [extra.copyright]
        name = "CC BY 4.0"
        url = "https://creativecommons.org/licenses/by/4.0/"


[languages]
    [languages.fr]
        title = "Luna"
        description = "Moi, c'est Luna (elle). Je vis en Bretagne et j'étudie au Lycée Expérimental de Saint-Nazaire. Je fais de la photographie, de la musique, du développement informatique, et je milite dans différents domaines."
        generate_feed = true
        feed_filename = "atom.xml"
        taxonomies = [
            { name = "tags", feed = true, paginate_by = 5  },
            { name = "categories", feed = true, paginate_by = 5 },
            { name = "projets", feed = true, paginate_by = 5 }
        ]

    [languages.en]
        title = "Luna"
        description = "I'm Luna (she). I live in Brittany (France) and i study at Lycée Expérimental de Saint-Nazaire. I'm a photographer, music artist, developer, and Activist."
        generate_feed = true
        feed_filename = "atom.xml"
        taxonomies = [
            { name = "tags", feed = true, paginate_by = 5  },
            { name = "categories", feed = true, paginate_by = 5 },
            { name = "projets", feed = true, paginate_by = 5 }
        ]


    [languages.fr.translations]
        post = "Posté"
        category = "Catégorie"
        tag = "Tag"
        search = "Rechercher"

        404_message = "Cette page n'existe pas ou plus !"

        by = "Par"
        posted = "Posté"
        updated = "Mis à jour"
        categories = "Catégories"
        tags = "Tags"
        share = "Partager"
        contact = "Me contacter"

        next = "Suivant"
        previous = "Précédent"

        contact_inquiries = "N'hésite pas à me contacter si vous tu as des questions concernant mes centres d'intérêt ou les valeurs que je défends (ressources, informations, aide pour le développement de sites web, etc.)."
        email = "luna[at]kaz.bzh"
        listen_music = "Écouter ma musique"
        music_description = "Je crée principalement de la musique électronique avec des éléments de rock, de punk ou expérimentaux. N'hésite pas à l'écouter."
        view_photos = "Consulter mes photos"
        photos_description = "Je prends des photos de paysages et d'astrophotographie. Jetes-y un coup d'œil."
        other = "Autres"
        other_links_description = "Autres liens utiles"
        developed_with = "Développé avec"
        source = "Code source"
        hosted_by = "Hébergé par"

        home = "Accueil"
        blog = "Blog"
        projects = "Projets"
        musics = "Musiques"
        photos = "Photos"
        about = "A propos"
        contactnav = "Contact"

    [languages.en.translations]
        post = "Post"
        category = "Category"
        tag = "Tag"
        search = "Search"

        404_message = "Page not found"

        by = "By"
        posted = "Posted"
        updated = "Updated"
        categories = "Categories"
        tags = "Tags"
        share = "Share"
        contact = "Contact Me"

        next = "Next"
        previous = "Previous"

        contact_inquiries = "Feel free to contact me if you have any inquiries regarding my interests or the values I stand for (resources, information, help with website development, etc.)."
        email = "luna[at]kaz.bzh"
        listen_music = "Listen to My Music"
        music_description = "I mainly make electronic music with elements of rock, punk, or experimental. Feel free to give it a listen."
        view_photos = "View My Photos"
        photos_description = "I take photos of landscapes and astrophotography. Take a look."
        other = "Other"
        other_links_description = "Other useful links"
        developed_with = "Developed with"
        source = "Source"
        hosted_by = "Hosted by"

        home = "Home"
        blog = "Blog"
        musics = "Musics"
        photos = "Photos"
        projects = "Projects"
        about = "About"
        contactnav = "Contact"

[markdown]
    highlight_code = true
    # extra_syntaxes_and_themes = []
    highlight_theme = "gruvbox-dark"

    render_emoji = true


    external_links_target_blank = true
    external_links_no_follow = true
    external_links_no_referrer = true

    smart_punctuation = false


[search]
    include_title = true
    include_description = false
    include_path = false
    include_content = true
    # truncate_content_length = 100


[link_checker]
    # skip_prefixes = []
    # skip_anchor_prefixes = []

    internal_level = "error"
    external_level = "error"


[slugify]
    paths = "on"
    taxonomies = "on"
    anchors = "on"